name: E2E Tests

on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: write
  contents: read
  issues: write
  statuses: write

jobs:
  Build:
    uses: ./.github/workflows/setup.yml

  SSL:
    needs: [Build]
    runs-on: ubuntu-latest
    steps:
      - name: Generate certificates for next step
        uses: kofemann/action-create-certificate@v0.0.4
        with:
          hostcert: "self-signed.crt"
          hostkey: "self-signed.key"
          cachain: "ca-chain.pem"

      - name: Archive artifacts
        run: zip -r ssl.zip . .dev/

  Tests:
    needs: [SSL]
    if: github.event.issue.pull_request && github.event.comment.body == '/e2e-tests'
    runs-on: ubuntu-latest
    steps:
      - name: Get PR branch
        uses: xt0rted/pull-request-comment-branch@v2
        id: comment-branch

      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}

      - name: Set latest commit status as pending
        uses: actions/github-script@v6
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.issue.number
            });

            const sha = pr.data.head.sha;
            const target_url = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;

            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: sha,
              state: 'pending',
              context: 'E2E Tests',
              description: `Status updated based on comment: ${context.payload.comment.body}`,
              target_url: target_url
            });

      - uses: dawidd6/action-download-artifact@v6
        with:
          name: build-artifacts
          github_token: ${{ secrets.PAT }}
          pr: ${{ github.event.pull_request.number || github.event.issue.number }}
          workflow: pull-request.yml

  Test-result:
    name: E2E result
    needs: [Tests]
    if: always() && github.event.comment.body == '/e2e-tests'
    runs-on: ubuntu-latest
    steps:
      - name: Get PR branch
        uses: xt0rted/pull-request-comment-branch@v2
        id: comment-branch

      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}

      - name: Set latest commit status as ${{ needs.Tests.result }}
        uses: actions/github-script@v6
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.issue.number
            });

            const sha = pr.data.head.sha;
            const target_url = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;

            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: sha,
              state: '${{ needs.Tests.result }}',
              context: 'E2E Tests',
              description: `Status updated based on comment: ${context.payload.comment.body}`,
              target_url: target_url
            });
