name: E2e Test Command
on:
  repository_dispatch:
    types: [e2e-test-command]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reactions: hooray

      - name: Running tests
        run: echo 'Running e2e tests...'
