name: Portal Pull Request Workflow
on:
  pull_request:

jobs:
  Checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR branch
        uses: xt0rted/pull-request-comment-branch@v2
        id: comment-branch
        with:
          repo_token: ${{ secrets.PATG }}

      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}

  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: "Lint"
        run: echo "Lint checking here"

  Setup:
    uses: ./.github/workflows/setup.yml
