name: Portal Pull Request Workflow
on:
  pull_request:

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: "Lint"
        run: echo "Lint checking here"

  Setup:
    runs-on: ubuntu-latest
    steps:
      - name: "Setup"
        run: echo "Set and Build"
