name: E2E Tests

on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: write
  contents: read
  issues: write
  statuses: write

jobs:
  Set-Status:
    if: github.event.issue.pull_request && github.event.comment.body == '/e2e-tests'
    runs-on: ubuntu-latest
    steps:
      - name: Get PR branch
        uses: xt0rted/pull-request-comment-branch@v2
        id: comment-branch

  Tests:
    if: github.event.issue.pull_request && github.event.comment.body == '/e2e-tests'
    needs: [Set-Status]
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "Running e2e tests..."'

      - name: Staging Tests ✅
        if: ${{ success() }}
        # set the merge commit status check
        # using GitHub REST API
        # see https://docs.github.com/en/rest/reference/repos#create-a-commit-status
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          --header 'authorization: Bearer ${{ secrets.PAT }}' \
          --header 'content-type: application/json' \
          --data '{
            "context": "Staging Tests",
            "state": "success",
            "description": "Staging tests passed",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'
      - name: Staging Tests 🚨
        if: ${{ failure() }}
        # set the merge commit status check
        # using GitHub REST API
        # see https://docs.github.com/en/rest/reference/repos#create-a-commit-status
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          --header 'authorization: Bearer ${{ secrets.PAT }}' \
          --header 'content-type: application/json' \
          --data '{
            "context": "Staging Tests",
            "state": "failure",
            "description": "Staging tests failed",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'

  Test-result:
    name: E2E result
    needs: [Tests]
    if: always() && github.event.comment.body == '/e2e-tests'
    runs-on: ubuntu-latest
    steps:
      - name: Add comment to PR
        uses: actions/github-script@v6
        with:
          script: |
            const name = '${{ github.workflow   }}';
            const url = '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}';
            const success = '${{ needs.Tests.result }}' === 'success';
            const body = `${name}: ${success ? 'succeeded ✅' : 'failed ❌'}\n${url}`;

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            })

      - name: Get PR branch
        uses: xt0rted/pull-request-comment-branch@v2
        id: comment-branch
