name: Portal Pull Request Workflow
on:
  pull_request:

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      run: echo "Lint checking here"

  Setup:
    runs-on: ubuntu-latest
    steps:
      run: echo "Set and Build"